server:
  port: 5000

postgres:
  host: localhost
  port: 5433
  user: postgres
  password: postgres
  dbname: test
  retries: 5
  interval: 5

service:
  output_buffer_length: 1

handler:
  default_offset: 0
  default_limit: 100